package Project.Hospital.Enums;

public enum Speciality {
    ANESTHESIOLOGY,
    INTERNAL_DISEASES,
    GASTROENTEROLOGY,
    ENDOCRINOLOGY,
    CARDIOLOGY,
    DERMATOLOGY,
    NEUROLOGY,
    NEPHROLOGY,
    PSYCHIATRY,
    RHEUMATOLOGY,
    GYNECOLOGY,
    ORTHOPEDICS,
    OPHTHALMOLOGY,
    UROLOGY,
    SURGERY
}
